packages:
  - 'apps/*'
  - 'packages/**'

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  vite: ^7.2.4
  typescript: ~5.9.3
  eslint: ^9.39.1
  '@types/node': ^24.10.1
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
